# Generated by Django 3.2.12 on 2023-05-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='taskstatus',
            field=models.CharField(choices=[('1', 'OPEN'), ('2', 'WORKING'), ('3', 'DONE'), ('4', 'OVERDUE')], default='OPEN', max_length=4),
        ),
    ]
