# Generated by Django 3.2.12 on 2023-05-31 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20230531_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='duedate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
